### ISSUE TITLE
Port validation repo?

### ISSUE THREAD

**Issue by MLopez-Ibanez** [boinor/boinor#13]
`README.md` mentions validation:

https://github.com/boinor/boinor/blob/81a01e34ddf3b23c80783d4d811846e80df89b80/README.md?plain=1#L183

But the validation repository (https://github.com/poliastro/validation/) has not been ported to the link mentioned there. I am not sure if porting the repository is enough or one should re-run the validation with @boinor once t make sure they still work after porting or whether those validation tests should be run as part of the CI.  

Perhaps @astrojuanlu  or @jorgepiloto  have a suggestion about those validation tests.

**Comment by astrojuanlu** [comment]
Those validation tests are triggered with the poliastro CI, so they should be ported too

**Comment by boinor** [comment]
But doesn't have to be a user secret available for the validation?

**Comment by MLopez-Ibanez** [comment]
In `https://github.com/boinor/validation/tree/main/.github/workflows`, you could create `trigger_validation.yaml` with:

```yaml
name: Trigger validation

on:
  workflow_call:
    inputs:
      boinor-branch:
        description: 'boinor branch to validate'
        default: 'main'
        required: false
        type: string
      validation-branch:
        description: 'validation branch to validate'
        default: 'main'
        required: false
        type: string

jobs:
  validation-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4
        repository: 'boinor/boinor'
        ref: ${{ inputs.boinor-branch }}
        path: boinor
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: install the package
        run: python3 -m pip install .
        working-directory: boinor

      - uses: actions/checkout@v4
        repository: 'boinor/validation'
        ref: ${{ inputs.validation-branch }}
        path: validation

      - run: run-validation.sh      
        working-directory: validation
```

and in https://github.com/boinor/boinor/blob/main/.github/workflows/validation_trigger.yml you could simply do:

```yml
# This workflow triggers boinor/validation CI from boinor/boinor
# everytime a new commit is introduced in boinor:main branch
name: Validation test cases

on:
  # A collection of events which trigger the validation action
  push:
    branches: [ main, actions ]
  release:

  # Enable manually to execute the actions
  workflow_dispatch:

jobs:
  # Validate boinor's new features
  validation:
    uses: boinor/validation/.github/workflows/trigger_validation.yml@main
    with:
      boinor-branch: ${{ github.ref }}
```
